name: test

on: [push]

jobs:
  build:
    name: PHP ${{matrix.php-version}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.2', '7,3', '7.4']

    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Use PHP ${{matrix.php-version}}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}
          coverage: "none"

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{steps.composercache.outputs.dir}}
          key: ${{runner.os}}-composer-${{hashFiles('**/composer.json')}}
          restore-keys: ${{runner.os}}-composer-

      - run: composer install --no-progress --prefer-dist --optimize-autoloader
      - run: composer test